# Generated by Django 4.0.4 on 2022-05-26 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blink', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='original_link',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='links',
            name='new_link',
        ),
    ]
