# Generated by Django 4.0.4 on 2022-06-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blink', '0002_rename_original_link_links_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='newlink',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
