# Generated by Django 4.0.4 on 2022-06-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blink', '0004_links_blink_links_link_3afd7a_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='element_id',
            field=models.IntegerField(default=0),
        ),
    ]
